//===----------------------------------------------------------------------===//
//
// This source file is part of the Soto for AWS open source project
//
// Copyright (c) 2017-2020 the Soto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Soto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by https://github.com/soto-project/soto-core/scripts/generate-region-tests.swift. DO NOT EDIT.

import SotoCore
import XCTest

class RegionTests: XCTestCase {
    func testStringToRegion() {
        let region = Region(awsRegionName: "eu-west-3")
        XCTAssertNotNil(region)
        XCTAssert(region! == Region.euwest3)
    }

    func testStringToInvalidRegion() {
        XCTAssertNil(Region(awsRegionName: "xxx"))
    }

    func testRegionEnumRawValue() {
        let region = Region(rawValue: "my-region")
        if Region.other("my-region") == region {
            XCTAssertEqual(region.rawValue, "my-region")
        } else {
            XCTFail("Did not construct Region.other()")
        }
    }

    func testRegionEnumExistingRegion() {
        var region: Region

        region = Region(rawValue: "af-south-1")
        if Region.afsouth1 == region {
            XCTAssertEqual(region.rawValue, "af-south-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for af-south-1")
        }

        region = Region(rawValue: "ap-east-1")
        if Region.apeast1 == region {
            XCTAssertEqual(region.rawValue, "ap-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-east-1")
        }

        region = Region(rawValue: "ap-northeast-1")
        if Region.apnortheast1 == region {
            XCTAssertEqual(region.rawValue, "ap-northeast-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-northeast-1")
        }

        region = Region(rawValue: "ap-northeast-2")
        if Region.apnortheast2 == region {
            XCTAssertEqual(region.rawValue, "ap-northeast-2")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-northeast-2")
        }

        region = Region(rawValue: "ap-northeast-3")
        if Region.apnortheast3 == region {
            XCTAssertEqual(region.rawValue, "ap-northeast-3")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-northeast-3")
        }

        region = Region(rawValue: "ap-south-1")
        if Region.apsouth1 == region {
            XCTAssertEqual(region.rawValue, "ap-south-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-south-1")
        }

        region = Region(rawValue: "ap-southeast-1")
        if Region.apsoutheast1 == region {
            XCTAssertEqual(region.rawValue, "ap-southeast-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-southeast-1")
        }

        region = Region(rawValue: "ap-southeast-2")
        if Region.apsoutheast2 == region {
            XCTAssertEqual(region.rawValue, "ap-southeast-2")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ap-southeast-2")
        }

        region = Region(rawValue: "ca-central-1")
        if Region.cacentral1 == region {
            XCTAssertEqual(region.rawValue, "ca-central-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for ca-central-1")
        }

        region = Region(rawValue: "cn-north-1")
        if Region.cnnorth1 == region {
            XCTAssertEqual(region.rawValue, "cn-north-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for cn-north-1")
        }

        region = Region(rawValue: "cn-northwest-1")
        if Region.cnnorthwest1 == region {
            XCTAssertEqual(region.rawValue, "cn-northwest-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for cn-northwest-1")
        }

        region = Region(rawValue: "eu-central-1")
        if Region.eucentral1 == region {
            XCTAssertEqual(region.rawValue, "eu-central-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-central-1")
        }

        region = Region(rawValue: "eu-north-1")
        if Region.eunorth1 == region {
            XCTAssertEqual(region.rawValue, "eu-north-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-north-1")
        }

        region = Region(rawValue: "eu-south-1")
        if Region.eusouth1 == region {
            XCTAssertEqual(region.rawValue, "eu-south-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-south-1")
        }

        region = Region(rawValue: "eu-west-1")
        if Region.euwest1 == region {
            XCTAssertEqual(region.rawValue, "eu-west-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-west-1")
        }

        region = Region(rawValue: "eu-west-2")
        if Region.euwest2 == region {
            XCTAssertEqual(region.rawValue, "eu-west-2")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-west-2")
        }

        region = Region(rawValue: "eu-west-3")
        if Region.euwest3 == region {
            XCTAssertEqual(region.rawValue, "eu-west-3")
        } else {
            XCTFail("Did not construct Region(rawValue:) for eu-west-3")
        }

        region = Region(rawValue: "me-south-1")
        if Region.mesouth1 == region {
            XCTAssertEqual(region.rawValue, "me-south-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for me-south-1")
        }

        region = Region(rawValue: "sa-east-1")
        if Region.saeast1 == region {
            XCTAssertEqual(region.rawValue, "sa-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for sa-east-1")
        }

        region = Region(rawValue: "us-east-1")
        if Region.useast1 == region {
            XCTAssertEqual(region.rawValue, "us-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-east-1")
        }

        region = Region(rawValue: "us-east-2")
        if Region.useast2 == region {
            XCTAssertEqual(region.rawValue, "us-east-2")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-east-2")
        }

        region = Region(rawValue: "us-gov-east-1")
        if Region.usgoveast1 == region {
            XCTAssertEqual(region.rawValue, "us-gov-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-gov-east-1")
        }

        region = Region(rawValue: "us-gov-west-1")
        if Region.usgovwest1 == region {
            XCTAssertEqual(region.rawValue, "us-gov-west-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-gov-west-1")
        }

        region = Region(rawValue: "us-iso-east-1")
        if Region.usisoeast1 == region {
            XCTAssertEqual(region.rawValue, "us-iso-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-iso-east-1")
        }

        region = Region(rawValue: "us-isob-east-1")
        if Region.usisobeast1 == region {
            XCTAssertEqual(region.rawValue, "us-isob-east-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-isob-east-1")
        }

        region = Region(rawValue: "us-west-1")
        if Region.uswest1 == region {
            XCTAssertEqual(region.rawValue, "us-west-1")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-west-1")
        }

        region = Region(rawValue: "us-west-2")
        if Region.uswest2 == region {
            XCTAssertEqual(region.rawValue, "us-west-2")
        } else {
            XCTFail("Did not construct Region(rawValue:) for us-west-2")
        }
    }
}
