name: API breaking changes

on:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6
    steps:
    - name: Install dependencies
      run: |
        apt-get update -qq
#         apt-get install -q -y git
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: API breaking changes
      run: |
        swift package diagnose-api-breaking-changes main
