name: API breaking changes

on:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6-focal
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: API breaking changes
      run: |
        swift package diagnose-api-breaking-changes main
#        git switch -c _diagnose-api-breaking-changes_
#        git checkout main
#        git checkout _diagnose-api-breaking-changes_
